import streamlit as st
import pandas as pd
import re
import json
import urllib.parse
from st_copy_button import st_copy_button
from streamlit_mic_recorder import speech_to_text

# --- IMPORT YOUR CUSTOM MODULES ---
import database
import llm
import sidebar
import audit_logger

# --- IMPORT NEW REFACTORED MODULES ---
from config.styles import HIDE_ST_STYLE
from utils.helpers import validate_email, validate_password_complexity, generate_outlook_link, generate_chat_title, convert_df_to_csv, convert_df_to_tsv
from components.auth import render_auth_ui
from components.dashboard import render_powerbi
from components.charts import render_custom_chart

# ==========================================
# 1. PAGE SETUP & MAGIC CSS
# ==========================================
st.set_page_config(
    page_title="BWGpt", 
    page_icon="🏢", 
    layout="centered", 
    initial_sidebar_state="expanded" 
)

st.markdown(HIDE_ST_STYLE, unsafe_allow_html=True)

# ==========================================
# 2. STATE INITIALIZATION & CALLBACKS
# ==========================================
if "logged_in" not in st.session_state: st.session_state.logged_in = False
if "current_session_id" not in st.session_state: st.session_state.current_session_id = None
if "current_user" not in st.session_state: st.session_state.current_user = "User"
if "current_department" not in st.session_state: st.session_state.current_department = ""
if "current_email" not in st.session_state: st.session_state.current_email = ""
if "chats" not in st.session_state: st.session_state.chats = {"New Chat": []}
if "current_chat" not in st.session_state: st.session_state.current_chat = "New Chat"
if "pinned_chats" not in st.session_state: st.session_state.pinned_chats = []
if "stop_gen" not in st.session_state: st.session_state.stop_gen = False
if "trigger_pbi_modal" not in st.session_state: st.session_state.trigger_pbi_modal = None

def stop_generation():
    st.session_state.stop_gen = True
    st.session_state.chats[st.session_state.current_chat].append({
        "role": "assistant",
        "content": "⚠️ This response was stopped."
    })

@st.dialog("Rename Chat")
def rename_dialog(chat_name):
    with st.form(key=f"rename_form_{chat_name}", border=False):
        new_name = st.text_input("Enter new name:", value=chat_name)
        submitted = st.form_submit_button("Save", type="primary", use_container_width=True)
        if submitted:
            if new_name and new_name != chat_name and new_name not in st.session_state.chats:
                updated_history = {}
                for k, v in st.session_state.chats.items():
                    if k == chat_name:
                        updated_history[new_name] = v
                    else:
                        updated_history[k] = v
                st.session_state.chats = updated_history
                
                if chat_name in st.session_state.pinned_chats:
                    st.session_state.pinned_chats.remove(chat_name)
                    st.session_state.pinned_chats.append(new_name)
                if st.session_state.current_chat == chat_name:
                    st.session_state.current_chat = new_name
                st.rerun()
            elif new_name == chat_name:
                st.rerun() 
            else:
                st.error("Name is already taken.")

# --- POWER BI POP-UP MODAL ---
@st.dialog("📊 Live Corporate Dashboard", width="large")
def dashboard_modal(filter_str=""):
    render_powerbi(filter_string=filter_str)

# --- EXPORT DRAWERS HELPER FUNCTION ---
def render_action_drawers(insights_text, unique_key):
    """Renders Outlook and Teams buttons matching Streamlit's native style."""
    
    # 1. Prepare the exact messages to be sent
    teams_msg = f"Hey team, sharing some corporate insights generated by BWGpt:\n\n{insights_text}"
    encoded_teams_msg = urllib.parse.quote(teams_msg)
    teams_href = f"https://teams.microsoft.com/l/chat/0/0?users=&message={encoded_teams_msg}"
    
    default_email_body = (
        f"Hi team,\n\n"
        f"I ran an analysis using BWGpt and wanted to share the following corporate data insights:\n\n"
        f"{insights_text}\n\n"
        f"Best regards,\n"
        f"{st.session_state.get('current_user', 'Team Member')}"
    )
    outlook_href = generate_outlook_link("", "BWGpt Data Analysis Summary", default_email_body)
    
    # 2. Render the clean buttons spread apart with text and emojis
    html_code = f"""
    <style>
    .share-btn-container {{
        display: flex;
        justify-content: space-between;
        width: 100%;
        margin-top: 15px;
        margin-bottom: 5px;
    }}
    .share-text-btn {{
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
        padding: 6px 16px; 
        border-radius: 8px;
        border: 1px solid rgba(128,128,128,0.2); 
        background-color: #ffffff;
        color: #31333F; 
        font-size: 14px;
        text-decoration: none;
        transition: all 0.2s ease-in-out;
    }}
    .share-text-btn:hover {{
        background-color: rgba(128,128,128,0.05);
        border-color: rgba(128,128,128,0.5);
        color: #FF4B4B; 
    }}
    </style>
    
    <div class="share-btn-container">
        <a href="{teams_href}" target="_blank" class="share-text-btn">
            💬 Teams
        </a>
        <a href="{outlook_href}" target="_blank" class="share-text-btn">
            📧 Outlook
        </a>
    </div>
    """
    
    st.markdown(html_code, unsafe_allow_html=True)
    
# ==========================================
# 3. MAIN APP ROUTING
# ==========================================
if not st.session_state.logged_in:
    render_auth_ui()
else:
    sidebar.render_sidebar(rename_dialog, dashboard_modal)

    # --- POP-UP MODAL TRIGGER CATCHER ---
    if "trigger_pbi_modal" in st.session_state and st.session_state.trigger_pbi_modal is not None:
        pbi_filter = st.session_state.pop("trigger_pbi_modal")
        dashboard_modal(filter_str=pbi_filter)

    # AUTO-POPUP ON LOGIN LOGIC
    if "has_seen_dashboard" not in st.session_state:
        st.session_state.has_seen_dashboard = False
        
    if not st.session_state.has_seen_dashboard:
        st.session_state.has_seen_dashboard = True
        dashboard_modal()

    st.title("🏢 BWGpt")
    current_chat_key = st.session_state.current_chat
    current_chat_history = st.session_state.chats[current_chat_key]
    
    chat_container = st.container()
    
    with chat_container:
        if len(current_chat_history) == 0:
            st.markdown(f"<h1 style='text-align: center; margin-top: 10vh;'>Welcome, {st.session_state.current_user}!</h1>", unsafe_allow_html=True)
            st.markdown("<p style='text-align: center; color: gray; font-size: 1.2rem;'>Ask me anything about your company data.</p>", unsafe_allow_html=True)

        for i, message in enumerate(current_chat_history):
            with st.chat_message(message["role"]):
                st.write(message["content"])
                
                # --- NEW REOPEN BUTTON LOGIC ---
                if message.get("is_dashboard"):
                    if st.button("📊 Reopen Dashboard", key=f"reopen_dash_{i}"):
                        dashboard_modal(filter_str=message.get("pbi_filter", ""))
                
                # Render Data Tables from history
                if "data_table" in message:
                    df = message["data_table"]
                    st.dataframe(df)
                    col1, spacer, col2 = st.columns([1.5, 6, 2.5])
                    with col1:
                        copy_text = convert_df_to_tsv(df)
                        st_copy_button(text=copy_text, before_copy_label="📋 Copy", after_copy_label="✅ Copied!", key=f"copy_{current_chat_key}_{i}")
                    with col2:
                        csv = convert_df_to_csv(df)
                        st.download_button(label="📥 Download", data=csv, file_name=f"BWGpt_Export_{i}.csv", mime="text/csv", key=f"dl_{current_chat_key}_{i}")
                
                # Render the Drawers from history
                if "full_insights" in message:
                    render_action_drawers(message["full_insights"], unique_key=f"hist_{i}")

    # ==========================================
    # --- CHAT INPUT & UPLOAD BAR (THE PILL) ---
    # ==========================================
    
    # Keeps the Mic and Upload buttons transparent
    st.markdown("""
        <style>
        div[data-testid="stPopover"] > button {
            background-color: transparent !important;
            border: none !important;
            box-shadow: none !important;
            font-size: 1.2rem !important;
        }
        div[data-testid="stPopover"] > button:hover {
            background-color: rgba(128, 128, 128, 0.1) !important;
        }
        </style>
    """, unsafe_allow_html=True)

    file_col, chat_col, mic_col = st.columns([1, 10, 1], vertical_alignment="center")
    
    with file_col:
        with st.popover("➕", help="Attach Context Files"):
            uploaded_files = st.file_uploader(
                "Upload files",
                type=["pdf", "xlsx", "docx", "xls", "doc"],
                accept_multiple_files=True,
                label_visibility="collapsed",
                key="chat_file_uploader"
            )
            if uploaded_files:
                st.success(f"✅ {len(uploaded_files)} file(s)")

    with chat_col:
        text_prompt = st.chat_input("Ask anything")
        
    with mic_col:
            voice_prompt = speech_to_text(
                language='en',
                start_prompt="🎙️",
                stop_prompt="⏹️",
                just_once=True,
                key='voice_input'
            )
            
    # --- HANDLE PROMPT LOGIC ---
    user_prompt = text_prompt or voice_prompt

    if user_prompt:
        if not user_prompt.strip():
            st.warning("⚠️ Please enter a valid question.")
            st.stop()
        
        if current_chat_key.startswith("New Chat"):
            new_title = generate_chat_title(user_prompt)
            base_title = new_title
            counter = 1
            while new_title in st.session_state.chats:
                new_title = f"{base_title} ({counter})"
                counter += 1
            
            updated_chats = {new_title: st.session_state.chats.pop(current_chat_key)}
            updated_chats.update(st.session_state.chats)
            st.session_state.chats = updated_chats
            st.session_state.current_chat = new_title
            current_chat_key = new_title 

        st.session_state.chats[current_chat_key].append({"role": "user", "content": user_prompt})
        
        with chat_container:
            with st.chat_message("user"):
                st.write(user_prompt)
                
            with st.chat_message("assistant"):
                # ==========================================
                # FAST-TRACK ROUTER INTERCEPTION
                # ==========================================
                with st.spinner("🧠 Analyzing request..."):
                    intent, pbi_filter = llm.check_intent(user_prompt)
                
                if intent == "DASHBOARD":
                    # --- FAST TRACK: Skip the database completely ---
                    success_msg = "Opening the corporate dashboard..."
                    if pbi_filter:
                        success_msg = f"Opening the dashboard filtered for: `{pbi_filter}`..."
                        
                    st.success(success_msg)
                    
                    st.session_state.chats[current_chat_key].append({
                        "role": "assistant",
                        "content": success_msg,
                        "pbi_filter": pbi_filter,
                        "is_dashboard": True
                    })
                    
                    st.session_state.trigger_pbi_modal = pbi_filter
                    st.rerun()
                
                else:
                    # ==========================================
                    # SLOW TRACK: Normal SQL Pipeline
                    # ==========================================
                    conn = database.get_connection()
                    if conn:
                        try:
                            db_schema = database.get_schema()
                            
                            stop_button_placeholder = st.empty()
                            response_placeholder = st.empty()
                            
                            st.session_state.stop_gen = False
                            
                            stop_button_placeholder.button("⏹ Stop Generation", type="primary", on_click=stop_generation, key="interrupt_trigger")
                            
                            full_response_text = ""
                            interrupted = False
                            
                            for token in llm.stream_sql(user_prompt, db_schema):
                                if st.session_state.stop_gen:
                                    interrupted = True
                                    break
                                
                                full_response_text += token
                                response_placeholder.code(full_response_text, language="sql")
                            
                            stop_button_placeholder.empty()
                            
                            if interrupted:
                                response_placeholder.warning("⚠️ This response was stopped.")
                                st.session_state.stop_gen = False
                                
                            else:
                                clean_sql = re.sub(r'```sql', '', full_response_text, flags=re.IGNORECASE)
                                clean_sql = re.sub(r'```', '', clean_sql).strip()
                                
                                response_placeholder.empty()

                                is_sql_query = any(keyword in clean_sql.upper() for keyword in ["SELECT", "EXEC ", "WITH ", "UPDATE ", "INSERT "])
                                
                                if is_sql_query:
                                    st.write("Here is the query I generated and ran:")
                                    st.code(clean_sql, language="sql")
                                    
                                    audit_logger.log_chat_query(
                                        login_id=st.session_state.current_email, 
                                        user_prompt=user_prompt, 
                                        generated_sql=clean_sql
                                    )
                                    
                                    df = database.execute_query(clean_sql, conn)
                                    
                                    if df is not None and not df.empty:
                                        st.dataframe(df)
                                        
                                        col1, spacer, col2 = st.columns([1.5, 6, 2.5])
                                        with col1:
                                            copy_text = convert_df_to_tsv(df)
                                            st_copy_button(text=copy_text, before_copy_label="📋 Copy", after_copy_label="✅ Copied!", key="copy_fresh_query")
                                        with col2:
                                            csv = convert_df_to_csv(df)
                                            st.download_button(label="📥 Download", data=csv, file_name="BWGpt_Export.csv", mime="text/csv", key="dl_fresh_query")
                                        
                                        st.session_state.chats[current_chat_key].append({
                                            "role": "assistant", 
                                            "content": f"Here is the query I generated and ran:\n```sql\n{clean_sql}\n```",
                                            "data_table": df
                                        })

                                        # PHASE 2: AI INSIGHTS GENERATION 
                                        if len(df) > 0:
                                            st.markdown("### AI Business Insights")
                                            insights_placeholder = st.empty()
                                            
                                            data_for_llm = df.head(20).to_markdown(index=False)
                                            
                                            full_insights = ""
                                            has_content = False
                                            
                                            for token in llm.stream_insights(user_prompt, data_for_llm):
                                                if token:
                                                    has_content = True
                                                    full_insights += token
                                                    insights_placeholder.markdown(full_insights)
                                            
                                            if not has_content:
                                                insights_placeholder.markdown("*No specific insights could be generated for this dataset.*")
                                            else:
                                                # (Leaving the regex checks in place just in case you ever want to add [CHART] back in the future!)
                                                pbi_match = re.search(r'\[PBI_FILTER\](.*?)\[/PBI_FILTER\]', full_insights)
                                                chart_match = re.search(r'\[CHART\](.*?)\[/CHART\]', full_insights, re.DOTALL)

                                                pbi_filter_string = pbi_match.group(1) if pbi_match else None
                                                chart_config = None

                                                if chart_match:
                                                    try:
                                                        chart_config = json.loads(chart_match.group(1))
                                                    except json.JSONDecodeError:
                                                        pass

                                                full_insights = re.sub(r'\[PBI_FILTER\].*?\[/PBI_FILTER\]', '', full_insights)
                                                full_insights = re.sub(r'\[CHART\].*?\[/CHART\]', '', full_insights, flags=re.DOTALL)
                                                
                                                insights_placeholder.markdown(full_insights)
                                                
                                                st.session_state.chats[current_chat_key].append({
                                                    "role": "assistant",
                                                    "content": f"### AI Business Insights\n{full_insights}",
                                                    "full_insights": full_insights
                                                })
                                                
                                                render_action_drawers(full_insights, unique_key="fresh")

                                                if pbi_filter_string:
                                                    st.info("Opening filtered corporate dashboard...")
                                                    st.session_state.trigger_pbi_modal = pbi_filter_string
                                                elif chart_config:
                                                    render_custom_chart(df=df, chart_config=chart_config)

                                    else:
                                        st.info("Query executed successfully, but no data was returned to analyze.")
                                        st.session_state.chats[current_chat_key].append({
                                            "role": "assistant", 
                                            "content": f"Query executed successfully, but no data returned:\n```sql\n{clean_sql}\n```"
                                        })
                                        
                                else:
                                    st.write(clean_sql)
                                    st.session_state.chats[current_chat_key].append({
                                        "role": "assistant", 
                                        "content": clean_sql
                                    })
                                
                        except Exception as e:
                            error_msg = f"Sorry, I encountered an error: {e}"
                            st.error(error_msg)
                            st.session_state.chats[current_chat_key].append({"role": "assistant", "content": error_msg})
                    else:
                        st.error("No database connection available.")
                        st.session_state.chats[current_chat_key].append({"role": "assistant", "content": "No database connection available."})
                    
            st.rerun()