import streamlit as st
import urllib.parse
from config.styles import HIDE_ST_STYLE
from utils.helpers import generate_outlook_link
from components.dashboard import render_powerbi

def init_session_state():
    """Initializes all required application session states securely."""
    # --- ADD THE USER DB BACK HERE ---
    if "user_db" not in st.session_state:
        st.session_state.user_db = {
            "admin@adityabirla.com": {
                "password": "Password123",
                "name": "Demo User",
                "department": "IT"
            }
        }

    if "logged_in" not in st.session_state: st.session_state.logged_in = False
    if "current_session_id" not in st.session_state: st.session_state.current_session_id = None
    if "current_user" not in st.session_state: st.session_state.current_user = "User"
    if "current_department" not in st.session_state: st.session_state.current_department = ""
    if "current_email" not in st.session_state: st.session_state.current_email = ""
    if "chats" not in st.session_state: st.session_state.chats = {"New Chat": []}
    if "current_chat" not in st.session_state: st.session_state.current_chat = "New Chat"
    if "pinned_chats" not in st.session_state: st.session_state.pinned_chats = []
    if "stop_gen" not in st.session_state: st.session_state.stop_gen = False
    if "trigger_pbi_modal" not in st.session_state: st.session_state.trigger_pbi_modal = None
    if "app_view" not in st.session_state: st.session_state.app_view = "chat"
    if "graph_chats" not in st.session_state: st.session_state.graph_chats = []
    if "has_seen_dashboard" not in st.session_state: st.session_state.has_seen_dashboard = False
    
def inject_custom_styles():
    """Injects core app branding and visibility constraints."""
    st.markdown(HIDE_ST_STYLE, unsafe_allow_html=True)

def stop_generation():
    """Safely interrupts active model token generation."""
    st.session_state.stop_gen = True
    st.session_state.chats[st.session_state.current_chat].append({
        "role": "assistant",
        "content": "⚠️ This response was stopped."
    })

@st.dialog("Rename Chat")
def rename_dialog(chat_name):
    """Brings up a dialog window overlay to change chat titles."""
    with st.form(key=f"rename_form_{chat_name}", border=False):
        new_name = st.text_input("Enter new name:", value=chat_name)
        submitted = st.form_submit_button("Save", type="primary", use_container_width=True)
        if submitted:
            if new_name and new_name != chat_name and new_name not in st.session_state.chats:
                updated_history = {}
                for k, v in st.session_state.chats.items():
                    if k == chat_name:
                        updated_history[new_name] = v
                    else:
                        updated_history[k] = v
                st.session_state.chats = updated_history
                
                if chat_name in st.session_state.pinned_chats:
                    st.session_state.pinned_chats.remove(chat_name)
                    st.session_state.pinned_chats.append(new_name)
                if chat_name in st.session_state.graph_chats:
                    idx = st.session_state.graph_chats.index(chat_name)
                    st.session_state.graph_chats[idx] = new_name
                if st.session_state.current_chat == chat_name:
                    st.session_state.current_chat = new_name
                st.rerun()
            elif new_name == chat_name:
                st.rerun() 
            else:
                st.error("Name is already taken.")

@st.dialog("📊 Live Corporate Dashboard", width="large")
def dashboard_modal(filter_str=""):
    """Launches the PowerBI embed code inside a large overlay window."""
    render_powerbi(filter_string=filter_str)

def render_action_drawers(insights_text, unique_key):
    """Renders functional sharing links for Microsoft Teams and Outlook."""
    teams_msg = f"Hey team, sharing some corporate insights generated by BWGpt:\n\n{insights_text}"
    encoded_teams_msg = urllib.parse.quote(teams_msg)
    teams_href = f"https://teams.microsoft.com/l/chat/0/0?users=&message={encoded_teams_msg}"
    
    default_email_body = (
        f"Hi team,\n\n"
        f"I ran an analysis using BWGpt and wanted to share the following corporate data insights:\n\n"
        f"{insights_text}\n\n"
        f"Best regards,\n"
        f"{st.session_state.get('current_user', 'Team Member')}"
    )
    outlook_href = generate_outlook_link("", "BWGpt Data Analysis Summary", default_email_body)
    
    html_code = f"""
    <style>
    .share-btn-container {{
        display: flex;
        justify-content: space-between;
        width: 100%;
        margin-top: 15px;
        margin-bottom: 5px;
    }}
    .share-text-btn {{
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 8px;
        padding: 6px 16px; 
        border-radius: 8px;
        border: 1px solid rgba(128,128,128,0.2); 
        background-color: #ffffff;
        color: #31333F; 
        font-size: 14px;
        text-decoration: none;
        transition: all 0.2s ease-in-out;
    }}
    .share-text-btn:hover {{
        background-color: rgba(128,128,128,0.05);
        border-color: rgba(128,128,128,0.5);
        color: #FF4B4B; 
    }}
    </style>
    
    <div class="share-btn-container">
        <a href="{teams_href}" target="_blank" class="share-text-btn">
            💬 Teams
        </a>
        <a href="{outlook_href}" target="_blank" class="share-text-btn">
            📧 Outlook
        </a>
    </div>
    """
    st.markdown(html_code, unsafe_allow_html=True)